<a href="https://colab.research.google.com/github/GOLISHYAMP/Colab_Notebooks/blob/main/NaiveBayesClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris
X,y = load_iris(return_X_y=True)

In [4]:
X[:5, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 31)

Lets start the naive bayes algo

In [7]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [8]:
y_pred = gnb.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


0.9666666666666667
[[ 8  0  0]
 [ 0 11  1]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.92      0.96        12
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



# **Iris dataset was having the feature values of continuous and which follows gaussian distributions**

Lets try with some mixed type of data

In [10]:
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# **Here we have the continuous type of data such as total_bill, tip as well as categorical bernoulli type features such as sex, smoker, time.**
# **Ok lets try on this dataset.**

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for i in ['sex', 'smoker', 'time']:
  df[i] = le.fit_transform(df[i])

In [13]:
df

total_bill   tip  sex  smoker   day  time  size
0         16.99  1.01    0       0   Sun     0     2
1         10.34  1.66    1       0   Sun     0     3
2         21.01  3.50    1       0   Sun     0     3
3         23.68  3.31    1       0   Sun     0     2
4         24.59  3.61    0       0   Sun     0     4
..          ...   ...  ...     ...   ...   ...   ...
239       29.03  5.92    1       0   Sat     0     3
240       27.18  2.00    0       1   Sat     0     2
241       22.67  2.00    1       1   Sat     0     2
242       17.82  1.75    1       0   Sat     0     2
243       18.78  3.00    0       0  Thur     0     2

[244 rows x 7 columns]

# **So, by using the above dataset lets try to predict the time whether it is lunch or dinner.**

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(drop = 'first'), [4])], remainder='passthrough')

In [15]:
df = ct.fit_transform(df)

In [17]:
df[:5, :]

array([[ 0.  ,  1.  ,  0.  , 16.99,  1.01,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.34,  1.66,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 21.01,  3.5 ,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 23.68,  3.31,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 24.59,  3.61,  0.  ,  0.  ,  0.  ,  4.  ]])

In [20]:
y = df[:,7]

In [21]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1.

In [26]:
X = df[:,[0,1,2,3,4,5,6,8]]

In [28]:
X[:5, :]

array([[ 0.  ,  1.  ,  0.  , 16.99,  1.01,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.34,  1.66,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 21.01,  3.5 ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 23.68,  3.31,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 24.59,  3.61,  0.  ,  0.  ,  4.  ]])

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 31)

Ok now our dataset is ready, now lets first try with Bernoulli NB

In [30]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(X_train, y_train)

BernoulliNB()

In [32]:
y_pred = bnb.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


0.9795918367346939
[[35  0]
 [ 1 13]]
              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99        35
         1.0       1.00      0.93      0.96        14

    accuracy                           0.98        49
   macro avg       0.99      0.96      0.97        49
weighted avg       0.98      0.98      0.98        49



# **Approx 98%, Thats good, Lets go with Guassian NB**

In [34]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [35]:
y_pred = gnb.predict(X_test)

In [36]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


0.9591836734693877
[[33  2]
 [ 0 14]]
              precision    recall  f1-score   support

         0.0       1.00      0.94      0.97        35
         1.0       0.88      1.00      0.93        14

    accuracy                           0.96        49
   macro avg       0.94      0.97      0.95        49
weighted avg       0.96      0.96      0.96        49



# **Ok this also good approx 96% accuracy**