<a href="https://colab.research.google.com/github/GOLISHYAMP/Colab_Notebooks/blob/main/RandomForestClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"Travel.Com" company wants to enable and establish a viable business model to expand the customer base. One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering - Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information. The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being.However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient.

We need to analyze the customers' data and information to provide recommendations to the Policy Maker and Marketing Team and also build a model to predict the potential customer who is going to purchase the newly introduced travel package.\
*Dataset link:*\
https://www.kaggle.com/datasets/susant4learning/holiday-package-purchase-prediction

In [167]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [168]:
df = pd.read_csv('/content/Travel.csv')

In [169]:
df.head()

CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0   
1      200001          0  49.0  Company Invited         1             14.0   
2      200002          1  37.0     Self Enquiry         1              8.0   
3      200003          0  33.0  Company Invited         1              9.0   
4      200004          0   NaN     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0   
1        Salaried    Male                       3                4.0   
2     Free Lancer    Male                       3                4.0   
3        Salaried  Female                       2                3.0   
4  Small Business    Male                       2                3.0   

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0   
1         Deluxe                    4.0      Divorced            2.0   
2          Basic                    3.0        Single            7.0   
3          Basic                    3.0      Divorced            2.0   
4          Basic                    4.0      Divorced            1.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   
2         1                       3       0                       0.0   
3         1                       5       1                       1.0   
4         0                       5       1                       0.0   

  Designation  MonthlyIncome  
0     Manager        20993.0  
1     Manager        20130.0  
2   Executive        17090.0  
3   Executive        17909.0  
4   Executive        18468.0

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   CustomerID                4888 non-null   int64  
 1   ProdTaken                 4888 non-null   int64  
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object 
 4   CityTier                  4888 non-null   int64  
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object 
 7   Gender                    4888 non-null   object 
 8   NumberOfPersonVisiting    4888 non-null   int64  
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object 
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object 
 13  NumberOfTrips             4748 non-null   float64
 14  Passport

In [171]:
df.shape

(4888, 20)

# **Data Cleaning**

Lets find the percentage of empty values in the each feature

In [172]:
li = [feature for feature in df.columns if df[feature].isna().sum() >= 1  ]
for feature in li:
  print(f'{feature} has {np.round(df[feature].isna().sum()/len(df) * 100, 2)}% null values' )

Age has 4.62% null values
TypeofContact has 0.51% null values
DurationOfPitch has 5.14% null values
NumberOfFollowups has 0.92% null values
PreferredPropertyStar has 0.53% null values
NumberOfTrips has 2.86% null values
NumberOfChildrenVisiting has 1.35% null values
MonthlyIncome has 4.77% null values


In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   CustomerID                4888 non-null   int64  
 1   ProdTaken                 4888 non-null   int64  
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object 
 4   CityTier                  4888 non-null   int64  
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object 
 7   Gender                    4888 non-null   object 
 8   NumberOfPersonVisiting    4888 non-null   int64  
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object 
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object 
 13  NumberOfTrips             4748 non-null   float64
 14  Passport

In [174]:
df.head()

CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0   
1      200001          0  49.0  Company Invited         1             14.0   
2      200002          1  37.0     Self Enquiry         1              8.0   
3      200003          0  33.0  Company Invited         1              9.0   
4      200004          0   NaN     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0   
1        Salaried    Male                       3                4.0   
2     Free Lancer    Male                       3                4.0   
3        Salaried  Female                       2                3.0   
4  Small Business    Male                       2                3.0   

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0   
1         Deluxe                    4.0      Divorced            2.0   
2          Basic                    3.0        Single            7.0   
3          Basic                    3.0      Divorced            2.0   
4          Basic                    4.0      Divorced            1.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   
2         1                       3       0                       0.0   
3         1                       5       1                       1.0   
4         0                       5       1                       0.0   

  Designation  MonthlyIncome  
0     Manager        20993.0  
1     Manager        20130.0  
2   Executive        17090.0  
3   Executive        17909.0  
4   Executive        18468.0

In [175]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [176]:
df['Gender'] = df['Gender'].replace({'Fe Male': 'Female'})

In [177]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [178]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [179]:
df['MaritalStatus'] = df['MaritalStatus'].replace({'Single': 'Unmarried'})

In [180]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

Lets fill the null values: \
type continuous with **median**\
and type catogory with **mode**

In [181]:
li = [(feature, df.dtypes[feature]) for feature in df.columns if df[feature].isna().sum() >= 1  ]
for i,j in li:
  print(i,' ',j)

Age   float64
TypeofContact   object
DurationOfPitch   float64
NumberOfFollowups   float64
PreferredPropertyStar   float64
NumberOfTrips   float64
NumberOfChildrenVisiting   float64
MonthlyIncome   float64


In [182]:
for i,_ in li:
  if i != 'TypeofContact':
    df[i].fillna(df[i].median(), inplace = True)
  else:
    df[i].fillna(df[i].mode(), inplace = True)

In [183]:
df.isnull().sum()

CustomerID                   0
ProdTaken                    0
Age                          0
TypeofContact               25
CityTier                     0
DurationOfPitch              0
Occupation                   0
Gender                       0
NumberOfPersonVisiting       0
NumberOfFollowups            0
ProductPitched               0
PreferredPropertyStar        0
MaritalStatus                0
NumberOfTrips                0
Passport                     0
PitchSatisfactionScore       0
OwnCar                       0
NumberOfChildrenVisiting     0
Designation                  0
MonthlyIncome                0
dtype: int64

Lets drop the customer Id columns no need of it

In [184]:
df.drop('CustomerID', axis = 1, inplace = True)

# **Feature Engineering**

In [185]:
df.head()

ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0          1  41.0     Self Enquiry         3              6.0   
1          0  49.0  Company Invited         1             14.0   
2          1  37.0     Self Enquiry         1              8.0   
3          0  33.0  Company Invited         1              9.0   
4          0  36.0     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0   
1        Salaried    Male                       3                4.0   
2     Free Lancer    Male                       3                4.0   
3        Salaried  Female                       2                3.0   
4  Small Business    Male                       2                3.0   

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0     Unmarried            1.0   
1         Deluxe                    4.0      Divorced            2.0   
2          Basic                    3.0     Unmarried            7.0   
3          Basic                    3.0      Divorced            2.0   
4          Basic                    4.0      Divorced            1.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   
2         1                       3       0                       0.0   
3         1                       5       1                       1.0   
4         0                       5       1                       0.0   

  Designation  MonthlyIncome  
0     Manager        20993.0  
1     Manager        20130.0  
2   Executive        17090.0  
3   Executive        17909.0  
4   Executive        18468.0

Here there are columns like NumberOfChildrenVisiting and NumberOfPersonVisiting so we can club it into a single column named NumberOfPeopleVisited

In [186]:
df['NumberOfPeopleVisited'] = df['NumberOfPersonVisiting']+ df['NumberOfChildrenVisiting']
df.drop(columns=['NumberOfPersonVisiting', 'NumberOfChildrenVisiting'], axis = 1, inplace = True)

In [187]:
df.head()

ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0          1  41.0     Self Enquiry         3              6.0   
1          0  49.0  Company Invited         1             14.0   
2          1  37.0     Self Enquiry         1              8.0   
3          0  33.0  Company Invited         1              9.0   
4          0  36.0     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfFollowups ProductPitched  \
0        Salaried  Female                3.0         Deluxe   
1        Salaried    Male                4.0         Deluxe   
2     Free Lancer    Male                4.0          Basic   
3        Salaried  Female                3.0          Basic   
4  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0     Unmarried            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0     Unmarried            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  \
0                       2       1     Manager        20993.0   
1                       3       1     Manager        20130.0   
2                       3       0   Executive        17090.0   
3                       5       1   Executive        17909.0   
4                       5       1   Executive        18468.0   

   NumberOfPeopleVisited  
0                    3.0  
1                    5.0  
2                    3.0  
3                    3.0  
4                    2.0

Lets find the total number of numerical, catogorical, discrete, continuous features

In [188]:
numerical = [ feature for feature in df.columns if df.dtypes[feature] != 'O']
print('number of numerical features = ', len(numerical))

number of numerical features =  12


In [189]:
catagorical = [ feature for feature in df.columns if df.dtypes[feature] == 'O']
print('number of catagorical features = ', len(catagorical))

number of catagorical features =  6


In [190]:
continuous = [ feature for feature in numerical if df[feature].nunique() > 25]
print('number of continuous features = ', len(continuous))

number of continuous features =  3


In [191]:
discrete = [ feature for feature in numerical if df[feature].nunique() <= 25]
print('number of discrete features = ', len(discrete))

number of discrete features =  9


Ok now lets do feature engineering on the catagorical features

In [192]:
df.head()

ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0          1  41.0     Self Enquiry         3              6.0   
1          0  49.0  Company Invited         1             14.0   
2          1  37.0     Self Enquiry         1              8.0   
3          0  33.0  Company Invited         1              9.0   
4          0  36.0     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfFollowups ProductPitched  \
0        Salaried  Female                3.0         Deluxe   
1        Salaried    Male                4.0         Deluxe   
2     Free Lancer    Male                4.0          Basic   
3        Salaried  Female                3.0          Basic   
4  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0     Unmarried            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0     Unmarried            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  \
0                       2       1     Manager        20993.0   
1                       3       1     Manager        20130.0   
2                       3       0   Executive        17090.0   
3                       5       1   Executive        17909.0   
4                       5       1   Executive        18468.0   

   NumberOfPeopleVisited  
0                    3.0  
1                    5.0  
2                    3.0  
3                    3.0  
4                    2.0

In [193]:
X = df.drop('ProdTaken', axis = 1)

In [194]:
y = df['ProdTaken']

In [195]:
category = X.select_dtypes(include = 'O').columns
numerical = X.select_dtypes(exclude = 'O').columns

Lets apply standard scaling on the numerical features and Onehot encoder on the categorical features

In [196]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

SC = StandardScaler()
OHC = OneHotEncoder(drop = 'first')

preprocessing = ColumnTransformer(
    [
        ('OneHotEncoder', OHC, category),
        ('StandardScaler', SC, numerical)
    ]
)

In [197]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 31)

In [198]:
X_train = preprocessing.fit_transform(X_train)
X_test = preprocessing.transform(X_test)

In [199]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier

models = {
    'LR' : LogisticRegression(),
    'KNN' : KNeighborsClassifier(),
    'NaiveB' : BernoulliNB(),
    'dtc' : DecisionTreeClassifier(),
    'rfc' : RandomForestClassifier()
}

In [200]:
from sklearn.metrics import accuracy_score, \
confusion_matrix, classification_report, precision_recall_curve

for model_name, model in list(models.items()):
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)

  print(f"Evaluation of {model_name} model ")
  print('Accuracy : ', accuracy_score(y_test, y_pred))
  print('Confusion Matrix : \n', confusion_matrix(y_test, y_pred))
  print('Classification : \n', classification_report(y_test, y_pred))
  print('precision_recall_curve : \n', precision_recall_curve(y_test, y_pred))
  print("\n *********************************************************\n")

Evaluation of LR model 
Accuracy :  0.8333333333333334
Confusion Matrix : 
 [[756  30]
 [133  59]]
Classification : 
               precision    recall  f1-score   support

           0       0.85      0.96      0.90       786
           1       0.66      0.31      0.42       192

    accuracy                           0.83       978
   macro avg       0.76      0.63      0.66       978
weighted avg       0.81      0.83      0.81       978

precision_recall_curve : 
 (array([0.19631902, 0.66292135, 1.        ]), array([1.        , 0.30729167, 0.        ]), array([0, 1]))

 *********************************************************

Evaluation of KNN model 
Accuracy :  0.8987730061349694
Confusion Matrix : 
 [[772  14]
 [ 85 107]]
Classification : 
               precision    recall  f1-score   support

           0       0.90      0.98      0.94       786
           1       0.88      0.56      0.68       192

    accuracy                           0.90       978
   macro avg       0.89 

So, we got the best model is RFC, So lets go with it and find do the hyperparameter tunning.

In [201]:
params = {
    'n_estimators' : [50, 100, 150, 200],
    'criterion' : ['gini', 'entropy', 'log_loss'],
    'max_depth' : [2,3,4,5,6,7],
    'class_weight' : ['balanced', 'balanced_subsample']
}

In [202]:
models = [
    ('rfc', RandomForestClassifier(), params)
]

In [203]:
from math import e
from sklearn.model_selection import RandomizedSearchCV
for name, model, params in models:
  print(f'{name} is under going HP tunning')
  rscv = RandomizedSearchCV(estimator=model, \
                            param_distributions=params, n_jobs = -1, \
                            refit = True, cv = 5, scoring = 'accuracy')
  rscv.fit(X_train, y_train)
  print("Eval o/p")
  print(rscv.best_params_)
  print(rscv.best_score_)
  y_pred = rscv.predict(X_test)

  print(f"Evaluation of {name} model ")
  print('Accuracy : ', accuracy_score(y_test, y_pred))
  print('Confusion Matrix : \n', confusion_matrix(y_test, y_pred))
  print('Classification : \n', classification_report(y_test, y_pred))
  print('precision_recall_curve : \n', precision_recall_curve(y_test, y_pred))
  print("\n ******************************************************\n")


rfc is under going HP tunning
Eval o/p
{'n_estimators': 200, 'max_depth': 7, 'criterion': 'entropy', 'class_weight': 'balanced'}
0.8480818414322251
Evaluation of rfc model 
Accuracy :  0.8578732106339468
Confusion Matrix : 
 [[698  88]
 [ 51 141]]
Classification : 
               precision    recall  f1-score   support

           0       0.93      0.89      0.91       786
           1       0.62      0.73      0.67       192

    accuracy                           0.86       978
   macro avg       0.77      0.81      0.79       978
weighted avg       0.87      0.86      0.86       978

precision_recall_curve : 
 (array([0.19631902, 0.61572052, 1.        ]), array([1.      , 0.734375, 0.      ]), array([0, 1]))

 ******************************************************

